server:
  port: 8000
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
chatgpt:
  api-key: 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   # https://beta.openai.com/docs/quickstart/adjust-your-settings
  max-tokens: 1000
#spring:
#  cloud:
#    azure:
#      active-directory:
#        enabled: true
#        profile:
#          tenant-id: 8398dce0-ce72-4b68-857e-9ba585008d3e
#        credential:
#          client-id: dff403fb-0fe5-413b-888a-be22b5de238c
#          client-secret: 3c4ee371-ac7a-426b-bc2d-76d166eda39e
#        authorization-clients:
#          graph:
#            scopes: https://graph.microsoft.com/Analytics.Read, email
logging:
  level:
    root: info
#    org.springframework.web: DEBUG
#    guru.springframework.controllers: DEBUG
#    org.hibernate: DEBUG
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
azure:
  application-insights:
    instrumentation-key: 0fbdefac-4b5b-4a1d-aeb9-af7711ff32f3
    enabled: true
    web:
      enabled: true
    logger:
      level:
        root: info
slack:
  webhook: https://hooks.slack.com/services/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